const { verifyToken, store_user_verification } = require("../../UTILS/endpoints.UTIL")
const User = require("../../DB/models/user.MODEL")
const Store = require("../../DB/models/store.MODEL")
const Client = require("../../DB/models/client.MODEL")
const bcrypt = require("bcrypt")
const Contable = require("../../DB/models/contable.MODEL")
const Credits = require("../../DB/models/bills.MODEL")